name: Publish Docker Image

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.0.0

      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: supporterino/stuv-backend
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
